replicaCount: 2

image:
  repository: docker.io/YOUR_DOCKERHUB_USERNAME/pos-validation-sdk
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000

backendConfig:
  enabled: true
  healthCheck:
    requestPath: /healthz
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2

env:
  PORT: "3000"
  TBC_ENDPOINT: "https://api.try.thecouponbureau.org"

redis:
  enabled: true
  host: ""
  port: "6379"
  image:
    repository: redis
    tag: "6.2"
    pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
