apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pos-validation-sdk.fullname" . }}
  labels:
    {{- include "pos-validation-sdk.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "pos-validation-sdk.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pos-validation-sdk.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: PORT
              value: {{ .Values.env.PORT | quote }}
            - name: REDIS_HOST
              value: {{ include "pos-validation-sdk.redisHost" . | quote }}
            - name: REDIS_PORT
              value: {{ .Values.redis.port | quote }}
            - name: TBC_ENDPOINT
              value: {{ .Values.env.TBC_ENDPOINT | quote }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
